apiVersion: v1
kind: Secret
metadata:
  name: {{ include "__SERVICE_NAME__.fullname" . }}
  labels:
    {{- include "__SERVICE_NAME__.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DATABASE: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%v/%s" .Values.database.user .Values.database.password .Values.database.host (.Values.database.port | default 5432) (.Values.database.name | default "postgres") | quote }}
