apiVersion: v1
kind: Service
metadata:
  name: {{ include "__SERVICE_NAME__.fullname" . }}
  labels:
    {{- include "__SERVICE_NAME__.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "__SERVICE_NAME__.selectorLabels" . | nindent 4 }}
